"""
Lead capture — the entry point for every lead into the growth engine.

Every lead is:
  1. Assigned a unique ID
  2. Attributed to the source content piece (closes the content → revenue loop)
  3. Scored for quality and urgency
  4. Stored with full stage + LTV metadata
  5. Flagged for immediate human alert if hot enough

The source_content field is the critical bridge — it tells you
EXACTLY which Reel, post, or LinkedIn article generated a Rs 9L
distributor deal. That intelligence flows back into the content
optimizer to produce more of what works.

Usage:
    from content_generator.leads.lead_capture import record_lead

    # When a distributor DMs you on Instagram
    lead_id = record_lead(
        segment="distributor",
        contact="+91-98765-43210",
        name="Rajesh Sharma",
        company="Sharma Distributors",
        source_content="reel_1_day42",
        source_platform="instagram",
        engagement_type="direct_dm",
        notes="Interested in South Mumbai territory",
    )
    # → lead_id: "dist_20260609_001"
    # → score: 87.5 (hot — immediate alert)
    # → estimated_ltv: Rs 9,00,000

    # When a retailer fills your WhatsApp form
    lead_id = record_lead(
        segment="retailer",
        contact="+91-97654-32109",
        source_content="carousel_day15",
        engagement_type="whatsapp_inquiry",
    )
"""
from content_generator.core.ist_dates import today_ist
import datetime
import logging
import os

logger = logging.getLogger(__name__)

_COUNTER_PATH = os.path.join("output", ".lead_counter.txt")


def record_lead(
    segment: str,                    # consumer | retailer | distributor | modern_trade
    contact: str          = "",      # phone number or email
    name: str             = "",
    company: str          = "",
    source_content: str   = "",      # content_id that drove this lead
    source_platform: str  = "",      # instagram | linkedin | whatsapp | youtube
    engagement_type: str  = "form_submission",
    notes: str            = "",
    initial_stage: str    = None,    # override default first stage
) -> str:
    """
    Record a new lead and return its unique lead_id.

    The lead is immediately:
      • Scored for quality
      • Assigned estimated LTV based on segment
      • Stored with full content attribution
      • Flagged for alert if hot (score >= 80)
    """
    from content_generator.leads.lead_scorer import score_lead, get_priority, should_alert
    from content_generator.leads.pipeline import PIPELINE_STAGES
    from content_generator.crm.value_calculator import estimate_ltv
    from content_generator.analytics.metrics_store import upsert_lead, record_pipeline_event

    # Determine initial pipeline stage
    stages = PIPELINE_STAGES.get(segment, ["inquiry"])
    stage  = initial_stage or stages[0]

    # Get source content viral score for scoring (if available)
    viral_score = _get_source_viral_score(source_content)

    # Score this lead
    score = score_lead(
        segment=segment,
        engagement_type=engagement_type,
        source_viral_score=viral_score,
        has_name=bool(name),
        has_phone=bool(contact),
        has_company=bool(company),
        stage=stage,
    )

    # Estimate LTV
    ltv = estimate_ltv(segment)

    # Generate unique lead ID
    lead_id = _generate_lead_id(segment)

    # Persist
    upsert_lead(
        lead_id=lead_id,
        segment=segment,
        stage=stage,
        name=name,
        contact=contact,
        source_content=source_content,
        source_platform=source_platform,
        score=score,
        estimated_ltv=ltv,
        notes=f"company={company} | {notes}".strip(" |") if company else notes,
    )

    # Log initial pipeline event
    record_pipeline_event(lead_id=lead_id, to_stage=stage, from_stage="", notes="Lead created")

    # Alert logic
    priority = get_priority(score)
    alert    = should_alert(score, segment)

    logger.info(
        "[leads] NEW %s lead '%s' | score=%.0f (%s) | ltv=Rs%.0f | source=%s | alert=%s",
        segment.upper(), lead_id, score, priority, ltv, source_content or "direct", alert,
    )

    if alert:
        _fire_hot_lead_alert(lead_id, segment, name, contact, score, source_content)

    return lead_id


def get_leads_from_content(content_id: str) -> list[dict]:
    """Return all leads generated by a specific content piece."""
    from content_generator.analytics.metrics_store import get_leads
    all_leads = get_leads()
    return [l for l in all_leads if l.get("source_content") == content_id]


def get_hot_leads(limit: int = 20) -> list[dict]:
    """Return leads with score >= 80, sorted by score descending."""
    from content_generator.analytics.metrics_store import get_leads
    from content_generator.leads.lead_scorer import enrich_lead_with_score
    leads = [enrich_lead_with_score(l) for l in get_leads()]
    hot   = [l for l in leads if l.get("score", 0) >= 80]
    return sorted(hot, key=lambda x: x["score"], reverse=True)[:limit]


def get_stalling_leads() -> list[dict]:
    """Return leads that have been stuck in a stage too long."""
    from content_generator.analytics.metrics_store import get_leads, _ensure_init, _conn
    from content_generator.leads.pipeline import is_stalling
    import sqlite3

    _ensure_init()
    leads = get_leads()
    stalling = []

    for lead in leads:
        segment = lead.get("segment", "consumer")
        stage   = lead.get("stage", "inquiry")
        created = lead.get("updated_at", lead.get("created_at", ""))

        if not created:
            continue
        try:
            updated_dt  = datetime.datetime.fromisoformat(created)
            days_in     = (datetime.datetime.now() - updated_dt).days
            if is_stalling(segment, stage, days_in):
                stalling.append({**lead, "days_in_stage": days_in})
        except (ValueError, TypeError):
            continue

    return sorted(stalling, key=lambda x: x.get("score", 0), reverse=True)


# ── Internal helpers ──────────────────────────────────────────────────────────

def _generate_lead_id(segment: str) -> str:
    """Generate a unique, human-readable lead ID."""
    prefix   = {"distributor": "dist", "modern_trade": "mt", "retailer": "ret", "consumer": "con"}
    date_str = today_ist().strftime("%Y%m%d")
    counter  = _next_counter()
    return f"{prefix.get(segment, 'unk')}_{date_str}_{counter:03d}"


def _next_counter() -> int:
    """Thread-safe incrementing daily counter for lead IDs."""
    os.makedirs("output", exist_ok=True)
    today = today_ist().isoformat()
    try:
        if os.path.exists(_COUNTER_PATH):
            with open(_COUNTER_PATH) as f:
                parts = f.read().strip().split(",")
                if len(parts) == 2 and parts[0] == today:
                    n = int(parts[1]) + 1
                    with open(_COUNTER_PATH, "w") as fw:
                        fw.write(f"{today},{n}")
                    return n
    except Exception as _e:
        logger.debug("[lead_capture] optional step failed: %s", _e)
    with open(_COUNTER_PATH, "w") as f:
        f.write(f"{today},1")
    return 1


def _get_source_viral_score(source_content: str) -> float:
    """Look up the viral score of the content piece that generated this lead."""
    if not source_content:
        return 50.0
    try:
        from content_generator.analytics.metrics_store import _ensure_init, _conn
        _ensure_init()
        with _conn() as con:
            row = con.execute("""
                SELECT viral_score FROM content_metrics
                WHERE content_id=? ORDER BY created_at DESC LIMIT 1
            """, (source_content,)).fetchone()
        return float(row["viral_score"]) if row else 50.0
    except Exception:
        return 50.0


def _fire_hot_lead_alert(
    lead_id: str, segment: str, name: str,
    contact: str, score: float, source_content: str,
) -> None:
    """Send hot lead alert via watchdog alert channels."""
    try:
        from content_generator.scheduler.watchdog import _alert
        msg = (
            f"HOT LEAD CAPTURED\n"
            f"  ID:       {lead_id}\n"
            f"  Segment:  {segment.upper()}\n"
            f"  Name:     {name or '(unknown)'}\n"
            f"  Contact:  {contact or '(unknown)'}\n"
            f"  Score:    {score:.0f}/100\n"
            f"  Source:   {source_content or 'direct'}\n"
            f"  Action:   Respond within 24 hours"
        )
        _alert(msg)
    except Exception as e:
        logger.warning("[leads] Alert failed: %s", e)
